### ISSUE TITLE
No replication done

### ISSUE THREAD

**Issue by kazoooka** [rubyrep/rubyrep#65]
Hi there, i set up the JRuby version as follows: 

```
RR::Initializer::run do |config|
  config.left = {
    :adapter  => 'postgresql', # or 'mysql2'
    :database => 'test',
    :username => 'npss',
    :password => 'secret',
    :host     => '127.0.0.1'
  }

  config.right = {
    :adapter  => 'postgresql',
    :database => 'test',
    :username => 'npss',
    :password => 'secret',
    :host     => '192.168.0.23'
  }
 
  config.options[:sync_conflict_handling] = :left_wins
  config.options[:database_connection_timeout] = 60
  config.include_tables /./
end
```

It's starting to do something but the replication is not done. So i added a new table on the right database - added some data to that - all that while rubyrep was running and saying  Starting replication in the last line of the dos window.   
I thought this is a multi master system where i could add data on a backup system and it would get transfered to the master and vice verca... ?  What configuration am  i doing wrong?

**Comment by alehmann** [comment]
rubyrep replicates data, not data structures (like table definitions).
Accordingly I am closing this issue.

**Comment by alehmann** [comment]
Just to note: I personally use ActiveRecord migrations to keep the schemas in my database servers in sync.
In the non-ruby/rails world there are similar tools. E.g.: https://flywaydb.org
