### ISSUE TITLE
Replication does not complete

### ISSUE THREAD

**Issue by ccbamatx** [rubyrep/rubyrep#66]
I am new to rubyrep.

Regardless of what I try... I cant seem to complete a replication.

Here are the config lines in the .conf file:
  config.include_tables /./ # regexp matching all tables in the database
  config.exclude_tables 'schema_migrations'
  config.exclude_tables 'plugin_schema_info'
  config.options[:auto_key_limit] = 2

On the right side... I start with an empty schema and the only tables that get created are:
  rr_pending_changes
  rr_running_flags

On the left side... three new tables are created:
  rr_logged_events
  rr_pending_changes
  rr_running_flags

Is there a log file or something else that I can check?

I am running on Windows 10, 64 bit, rubyrep version 2.0.0

This behavior happens regardless if I try: 
postgresql -> mysql
mysql -> mysql
postgresql -> postgresql

Thanks for the help.

**Comment by ccbamatx** [comment]
I think the problem is the empty schema on the right side.

Is there a way to sync the tables from the left side to an empty schema on the right side?

**Comment by alehmann** [comment]
Indeed, rubyrep only replicates data, not data structures (table definitions, etc.). 
There are other tools for keeping schemas up-to-date in multiple databases. I personally use ActiveRecord migrations. Similar tools exist in the non-ruby/rails world. A quick google shows e.g.: https://flywaydb.org.

I am closing this issue.
