### ISSUE TITLE
Replication of PostgreSQL db fails with malformed array literal error...

### ISSUE THREAD

**Issue by mitch-shiver** [rubyrep/rubyrep#67]
I am getting the following error when trying to replicate two PostgreSQL databases, This happens on every attempt to update the target db from the source db.  has anyone seen this before?  Looking here and elsewhere it appears to be related to copying an array but using the wrong brackets ('[...]' instead of '{...}').  Sync fails with the same error as the second one below; scan does not fail (but not surprising as it is not attempting to write to the target db):

"insert failed with ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: malformed array literal: "---<array of numbers>"

Another instance (seems to support the bracketing issue I read about online):
"insert failed with ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: malformed array literal: "--- SE
  Detail: Array value must start with "{" or dimension information.
  Position: 361: insert... "

Please help, I love this tool and want to use it, but this is a deal-breaker currently.

**Comment by alehmann** [comment]
This was a bug. Postgres specific fields like arrays and JSON were not written correctly.
I released version 2.0.2 with a bug fix. Please try with that version.
I am tentatively closing this issue.

**Comment by penguincoder** [comment]
Sorry to comment on this closed ticket, but does this also work for hstore columns? I was just working on a local fork of this to correct the behavior of both hstore and array values when copying them. You have specifically mentioned arrays, but I just wanted to check before I made a PR for the hstore changes.
